make clean
make MODEL=DIFFUSION_$1 BT=PRIORITY_QUEU_SUPER_OPTIMIZATION STO=STOCHASTIC_OPTIMIZATION RE=NON_REUSE_RANDOM_NUMBER
mv DIFFUSION_$1 $1_4
mv DIFFUSION_$1_COMPILATION_OPTIONS.txt $1_4_COMPILATION_OPTIONS.txt
make clean
make MODEL=DIFFUSION_$1 BT=BINARY_TREE_SUPER_OPTIMIZATION STO=STOCHASTIC_OPTIMIZATION RE=REUSE_RANDOM_NUMBER
mv DIFFUSION_$1 $1_33
mv DIFFUSION_$1_COMPILATION_OPTIONS.txt $1_33_COMPILATION_OPTIONS.txt
make clean
make MODEL=DIFFUSION_$1 BT=BINARY_TREE_SUPER_OPTIMIZATION STO=STOCHASTIC_OPTIMIZATION RE=NON_REUSE_RANDOM_NUMBER
mv DIFFUSION_$1 $1_3
mv DIFFUSION_$1_COMPILATION_OPTIONS.txt $1_3_COMPILATION_OPTIONS.txt
make clean
make MODEL=DIFFUSION_$1 BT=BINARY_TREE_OPTIMIZATION STO=STOCHASTIC_OPTIMIZATION RE=NON_REUSE_RANDOM_NUMBER
mv DIFFUSION_$1 $1_2
mv DIFFUSION_$1_COMPILATION_OPTIONS.txt $1_2_COMPILATION_OPTIONS.txt
make clean
make MODEL=DIFFUSION_$1 BT=NON_BINARY_TREE_SUPER_OPTIMIZATION STO=STOCHASTIC_OPTIMIZATION RE=NON_REUSE_RANDOM_NUMBER
mv DIFFUSION_$1 $1_1
mv DIFFUSION_$1_COMPILATION_OPTIONS.txt $1_1_COMPILATION_OPTIONS.txt
make clean
make MODEL=DIFFUSION_$1 BT=NON_BINARY_TREE_SUPER_OPTIMIZATION STO=NON_STOCHASTIC_OPTIMIZATION RE=NON_REUSE_RANDOM_NUMBER
mv DIFFUSION_$1 $1_0
mv DIFFUSION_$1_COMPILATION_OPTIONS.txt $1_0_COMPILATION_OPTIONS.txt
make clean
